### PR TITLE
android target: activity result callback

### PR DESCRIPTION
**Pull request by adamredwoods**
this is to allow the android target to be expanded by custom modules that need onActivityResultCallback() when using Activity Intents. good for cameras, IAP, contact lists, etc.

tested with camera, seems to work ok.

coders still need to modify manifest.xml.

### CODE REVIEW

**Comment by blitz-research** [comment]
Just been looking into similar stuff for Xaron...

Isn't it possible to create multiple activities? Wouldn't this be a better approach as opposed to playing 'catch up kludge' with all the possible things might want to do with an activity?

Or do some things _have_ to happen in the main activity?

Another alternative is to let users 'name' the main activity class, so a module can extend AndroidGame with it's own MonkeyGame-like class. The main issue here is that the trans builder gets a little more complicated.

**Comment by adamredwoods** [comment]
> > Isn't it possible to create multiple activities?  

probably. i gave a quick attempt but was unsuccessful.
this route seemed a little simpler, especially since it's basically a helper class for those wanting to extend monkey.

it's up to you, if you can find an example that makes sense, might be just as simple.

**Comment by blitz-research** [comment]
Ok, merged, tidied up a bit and pushed back to develop!

I'd _still_ like a more general purpose solution to 'how do you take over the Activity?', but this will do for now...

**Comment by blitz-research** [comment]
I'm actually warming to the approach a lot...

A few thoughts:
- I think the 'Update' method should be renamed to something like
  OnActivityResult. In general, I prefer interface methods names to be as
  specific as possible as you don't know what class they might end up in - it
  just reduces the changes of an interface method clashing with a class
  method.
- Perhaps IActivityResultCallback could be changed to a more complete
  IActivityDelegate which contains a bunch of methods that may be useful to
  modules, eg: OnPause, OnRestart etc. Perhaps everything in the 'protected
  methods' section here:
  http://developer.android.com/reference/android/app/Activity.html
- In which case, it may be easier to use if it's just a class, with default NOP
  implementations. This also allows us to add things without upsetting existing code.
- Also, perhaps it should be AddActivityDelegate instead of
  SetActivityDelegate - otherwise, how will people be able to use both IAP
  and camera?

Just some ideas...

**Comment by adamredwoods** [comment]
> > a more complete
> > IActivityDelegate which contains a bunch of methods that may be useful to
> > modules, eg: OnPause, OnRestart etc. Perhaps everything in the 'protected
> > methods' section here:  

true, after looking at Xaron's IAP, it needs to access the OnDestroy() as well to clean up properly.

> > AddActivityDelegate instead of
> > SetActivityDelegate - otherwise, how will people be able to use both IAP
> > and camera?  

my original thought was that the onActivityResultCallback would basically be controlled like a state machine, one activity delegate at a time, thus why i originally chose "SetActivity". but if you have a better idea, go with it. i just don't want you to run into too much maintenance upkeep.

**Comment by blitz-research** [comment]
> onActivityResultCallback would basically be controlled like a state
> machine, one activity delegate at a time,

Not quite sure what you mean there, but I was thinking of maintaining a
list of ActivityDelegates, so when OnPause happens, each delegate gets it's
OnPause method called.

This way, both IAP and camera modules can call AddActivityDelegate (without
having to be aware of each other) and both will get their OnPause (and
OnActivityResult etc) methods called when an OnPause etc happens. Just like
an EventListener system.

Sound OK?

> i just don't want you to run into too much maintenance upkeep.

Hopefully, this will keep everyone who wants to 'hook' Activity happy with
no extra effort from me - beyond perhaps having to add new methods to
ActivityDelegate every now and then.

**Comment by adamredwoods** [comment]
> > This way, both IAP and camera modules can call AddActivityDelegate

ok, i get it, makes sense.

**Comment by blitz-research** [comment]
Pushed new version to develop branch - haven't actually _tried_ it yet, but
things compile/run as usual!

Can you let me know if it looks OK/works?

Also, apps that implement onActivityResult will have to make sure to check
it's _their_ result in case multiple delegates have been added - not sure
how this can be done...?

I've provided methods for app lifecycle stuff as well as onActivityResult.
Could add more but would like to play it safe initially. More can be added
as people need them.

**Comment by adamredwoods** [comment]
ok works. cleaner. put the Android Camera Intent test code here:
http://monkeycoder.co.nz/Community/posts.php?topic=5502

> > apps that implement onActivityResult will have to make sure to check
> > it's _their_ result  

i think one way would be to return a unique id from AddActivityDelegate() to avoid duplicates. but i dont know if it's really needed, since usually only one activityforresult is executed at one time....?

**Comment by blitz-research** [comment]
Latest release has a new method BBAndroidGame.AllocateActivityResultRequestCode()

Use this to allocate in integer 'request code' that can be used when starting intent, so onActivityResult handlers can teel which result is 'theirs'.

See brl/native/monkeystore.android.java for example.

**Pull request closed without merging**
