### PR TITLE
ios return key fix

### PR DESCRIPTION
**Pull request by skn3**
I just fixed this bug:
http://monkeycoder.co.nz/Community/posts.php?topic=5133

The return key was not being trapped and was just being handled in the generic key handler.

### CODE REVIEW

**Comment by skn3** [comment]
Also fixed issue with space key (and possible other keys) causing random key events. Changed it so the change range function always returns YES.

**Comment by skn3** [comment]
Ok I think this is all working properly now...

**Comment by blitz-research** [comment]
Thanks!

I just pushed a modified version of this that doesn't let the textedit string grow 'forever' - probably not necessary...

**Comment by skn3** [comment]
winner :dart:

**Pull request closed without merging**
