### PR TITLE
added gamepad support to html5. Added gamepad example to bananas/skn3.

### PR DESCRIPTION
**Pull request by skn3**
Hey Mark,

I have added support to html5 for gamepad. It only maps to standard mapped gamepads, so if the browser cant recognise it then the code will ignore it. Seems to work ok for me on xbox 360 pad!

### CODE REVIEW

**Comment by therevills** [comment]
This is great! Top work skn3!

@marksibly any chance of adding this officially?

**Comment by StingerGames** [comment]
Yes please! Would be great for the NES jam.

**Comment by blitz-research** [comment]
I have attempted to merge this! Appears to work well, although I have also only tested with an xbox360 controller. You do get to use both triggers though!

Think the merge worked, but could someone who knows more about git clarify something?

I followed the command line instructions to merge it locally here first for testing, but was a bit confused by the step that looked like this (which you do after creating a branch):

git pull https://github.com/skn3-develop.git develop

(may not have been this exactly)

To me, this appears to pull skn3-develop 'develop' branch changes - but I only want to pull this one pull request.

So what happens if the skn3-develop develop branch has changed since the pull request was made?

Also, should I do a new release for game jamming purposes?

**Comment by ImmutableOctet** [comment]
@blitz-research Any thoughts on the jarring [GLFW input bottleneck](http://www.monkey-x.com/Community/posts.php?topic=10160)? I don't think we need to know if a controller was plugged in every frame.

Also, not sure if they would be useful, but the git docs may help: https://git-scm.com/docs/git-pull

**Comment by skn3** [comment]
Well by default the pull request will include any further commits that I have made since requesting to pull.

So the ideal situation would be for me to work in my own Dev branch and then have merged into my own master. I then pull request from master. I would then be free to mangle the Dev branch without it farking the pull request. But I generally don't commit anything but these tweaks to the monkey repo, so didn't bother.

**Comment by blitz-research** [comment]
> Well by default the pull request will include any further commits that I have made since requesting to pull.

Thanks for that. For some reason I was under the impression that pull requests were some kind of separate thing, like a discrete package of patches or something.

**Comment by skn3** [comment]
No problem. I thought so too at first (just because that would have made complete logic sense), but turns out nope. Comes in handy as a result but just have to be more mindful of commits when working In larger teams.

**Pull request merged**
