### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by adamredwoods**
i've always felt CC_OPTS should be added to the stdcpp.monkey target to help some of us extend monkey desktop targets.
very handy IMHO.

### CODE REVIEW

**Comment by adamredwoods** [comment]
its the last commit on that list, not sure why it listed that other stuff.

**Comment by blitz-research** [comment]
Sort of been waiting until I clean up preprocessor += until I did this, eg:

#CC_OPTS+="-o3"

Currently, += just separates things with ';' so this...

#CC_OPTS+="-o3"
#CC_OPTS+="-DYEAH"

...ends up as "-o3;-DYEAH" which would confuse gcc.

A Replace( ";"," " ) would deal to this, but it means you can't use ';' in any += strings.

But that's probably OK in this case - will add this to stdcpp soon!

CC_OPTS for glfw is a bigger issue due to msvc. Perhaps glfw should become 'mingw only'?

**Comment by adamredwoods** [comment]
so the += inserting semi-colons can be worked around by using

#CC_OPTS0 = "-lgl"
#CC_OPTS1 = "-lwin"
#CC_OPTS = CC_OPTS0+CC_OPTS1

which seems to work for now.

i think this would be a great start to just add it in the stdcpp, giving us tinkerers a little more room to play.
i'm not yet worried about the glfw targets using this, maybe for something like Cairo graphics, but no one's really demanding it (yet). cross that bridge later.

**Comment by blitz-research** [comment]
Sort of, but the point of the += is really to allow you to put things in
separate modules - so there are an 'unknown' number of CC_OPTSn=.

Anyway, added my own version to stdcpp which should work as long as you
don't have ; in an opt! Will give it a quick test and push it.

**Comment by blitz-research** [comment]
Pushed to develop!

**Pull request closed without merging**
